All: 
	pandoc x.md -s -o html_site/x.md.html -c ../templates/kult.css 
	pandoc y.md -s -o html_site/y.md.html -c ../templates/kult.css 
	pandoc Application_Installation_Conventions_and_Configuration.md -s -o html_site/Application_Installation_Conventions_and_Configuration.html -c ../templates/kult.css 
	open html_site/x.md.html

pwd:
	pwd >> ~/Desktop/x.txt
